# Generated by Django 5.2.6 on 2025-10-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTx',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('coins', models.IntegerField()),
                ('method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('pix', 'PIX'), ('admin', 'Admin')], max_length=10)),
                ('external_id', models.CharField(max_length=191)),
                ('created_at', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'coin_tx',
                'indexes': [models.Index(fields=['method', 'external_id'], name='uniq_method_ext'), models.Index(fields=['account_id', 'created_at'], name='idx_account_time')],
                'unique_together': {('method', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='PixTx',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('txid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('account_id', models.IntegerField()),
                ('pack_id', models.CharField(max_length=32)),
                ('coins', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('provider', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('qr_emv', models.TextField(blank=True, null=True)),
                ('qr_base64', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.IntegerField()),
                ('expires_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pix_tx',
                'indexes': [models.Index(fields=['provider', 'external_id'], name='unique_provider_ext')],
            },
        ),
    ]
